---
title: "Notes: Ask Questions to Make Data-Driven Decisions"
author: "Wonnetz Phanthavong"
output: pdf_document
urlcolor: blue
---
\begin{center}
email: \textcolor{blue}{wonnetz@protonmail.com} \\
linkedin: \textcolor{blue}{https://www.linkedin.com/in/wonnetz/}  
\end{center}

# Abstract 
Here you will find the notes for the second course of the Google Data Analytics Professional Certificate. There are 6 other courses in the sequence. These are the key topics.  

* Effective/S.M.A.R.T. Questions  
* Quantitative Data vs. Qualitative Data  
* Spreadsheets Basics 
  * Functions, Formulas  
  * Pivot Tables, Graphs  
  * Visual Organization  
* Structured Thinking  
* Key Communication Skills  

\newpage
# Week 1: Intro to Problem-Solving and Effective Questioning
## The Six Data Analysis Phases, Reviewed
1. Ask  
What are my stakeholders saying their problems are?  
Now that I've identified the issue, how can I help the stakeholders resolve their question?

2. Prepare  
What do I need to figure out how to solve this problem?  
What research do I need to do?

3. Process  
What data errors or inaccuracies might get in my way of getting the best possible answer to the problem I am trying to solve?  
How can I clean my data so the information I have is more consistent?  

4. Analyze  
What story is the data telling me?  
How will my data help me solve the problem?  
Who needs my company’s product or service? What type of person is most likely to use it?  

5. Share  
How can I make what I present to the stakeholders engaging and easy to understand?  
What would help me understand this if I were the listener?  

6. Act  
How can I use the feedback I received during the share phase (step 5) to actually meet the stakeholder’s needs and expectations?  

## Structured thinking 
1. Reorganizing the current problem or situation  
2. Organizing available information  
3. Revealing gaps and opporunities  
4. Identifying your options  

## Six Basic Problem Types
1. Making Predictions  
2. Categorizing Things  
3. Spotting Something Unusual  
4. Identifying Themes  
5. Discovering Connections  
6. Finding Patterns

## S.M.A.R.T Questions
- S: Specific  
  - Specific questions are simple, significant, and focused  
- M: Measurable  
  - Measurable questions can be quantified and assessed  
- A: Action-Oriented  
  - Action-oriented questions encourage change  
- R: Relevant  
  - Relevant questions matter, are important, and have significance to the problem at hand  
- T: Time-Bounded  
  - Time bound questions specify the period to be studied  
  
## Questions to Avoid
- Leading Questions: "This product is too expensive, isn't it?"
  - A better question to ask is, "What is your opinion of the price of this product?" or "What price range would make you consider this product?".
- Closed Ended Questions: "Were you satisfied with the customer trial?"
  - A better question to ask is, "Can you tell me about your experience with the trial?"
- Vague Questions: "Does the tool work for you?"
  - A better question to ask is, "When it comes to yard work, how much time has the tool saved you?"

\newpage
# Week 2: Data and Decisions
## Quantitative Data vs. Qualitative Data
- Quantitative Data, measures numerical facts
  - The what?
  - How many?
  - How often?
- Qualitative Data, adds context 
  - Why do you like this?
  - Why are the numbers the way they are?

## Sharing Your Findings
- Reports
  - Pros: 
    - High Level Historical Data
    - Easy to Design
    - Pre-Cleaned and Sorted Data
  - Cons:
    - Continual Maintenance 
    - Less Visually Appealing
    - Static
- Dashboards
  - Pros:
    - Dynamic, Automatic, and Interactive
    - More Stakeholder Access
    - Low Maintenance
  - Cons:
    - Labor-Intensive Design
    - Can be Confusing
    - Potentially Uncleaned Data
  
## Creating a Dashboard
- Identify the Stakeholders who need to see the data and how they will use it  
  - Ask the stakeholders effective questions  
  - [Cheat Sheet](https://s3.amazonaws.com/looker-elearning-resources/Requirements+Gathering+Worksheet.pdf)  
- Design the Dashboard (what should be displayed)
  - Use a clear header, short text descriptions, display the most important info  
- Select the Visualizations  
  - Changes over time? Line and Bar Graphs
  - Comparison to the whole? Pie and Donut Charts
  
## Types of Dashboards
1. Strategic: Focuses on long term goals and strategies at the highest level of metrics
2. Operational: Short-term performance tracking and intermediate goals
3. Analytical: Consists of the datasets and the mathematics used in these sets

# Week 3: Spreadsheets
## Formulas vs. Functions
- The overall idea of a formula is that it is entered by the user. It starts with an equal sign '=' and it is followed by basic math operations.  
- The main point of a function is that it is pre-defined by the spreadsheet application.  
Both of these have similar purposes. 

## Scope of Work (SOW)
A scope of work is designed to keep the team on the same page. It also ensures that the contributors, sponsers, and stakeholders share the same understanding of the relevant details.  

What makes a good SOW?  
1. Deliverables  
  - What work is being done? How will we collect the data and for how long? How will we share the analysis?  
2. Milestones  
  - What are the major milestones of this project? How do you know if a milestone is considered complete?  
3. Timeline  
  - How long will the deliverables be completed? How long do we expect the project to last?  
4. Reports  
  - How will we communicate with stakeholders and sponsers? Will progress be reported weekly? Monthly? When milestones are complete? What information will the reports hold?  

## How to contextualize raw data into meaningful information?
- Who: The person or organization that created, collected, and/or funded the data collection  
- What: The things in the world that data could have an impact on  
- Where: The origin of the data  
- When: The time when the data was created or collected  
- Why: The motivated behind the creation or collection  
- How: The method used to create or collect it  

# Week 4: Communicating with your Team
## Different Kinds of Stakeholders
1. The Executive Team  
2. Customer-Facing Team  
3. Data Science Team

## Working Effectively with Stakeholders
- Discuss Goals  
- Plan for the Unexpected  
- Start with words and visuals  
- Communicate Often

## Keys to Clear Communication
1. Who is your audience?  
2. What do they already know?  
3. What do they need to know to move forward?  
4. How can we communicate that effectively to them?

## Limitations of Data
- Incomplete or Nonexistent Data  
- Don't Miss Misaligned Data
  - If you're using data from another team, make sure that you understand their metrics for their data
- Deal with Dirty Data
  - Fixing or removing incorrect, corrupted, or incorrectly formatted, duplicate, or incomplete data within a dataset
- Tell A Clear Story
  - Compare the same types of data  
  - Visualize with care  
  - Leave out needless graphs  
  - Test for statistical significance 
  
